openapi: 3.1.0
info:
  title: Alice API
  description: API publique d'Alice (GPTPortail) - Mémoire + Communication Agents Vitaux
  version: 1.0.0
servers:
  - url: https://gptportail-production.up.railway.app

paths:
  /alice/poser-question:
    post:
      operationId: poserQuestionAlice
      summary: Poser une question à Alice (mémoire + GPT-4)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
              required:
                - question
      responses:
        "200":
          description: Réponse d'Alice
          content:
            application/json:
              schema:
                type: object
                properties:
                  reponse:
                    type: string

  /alice/ajouter-memoire:
    post:
      operationId: ajouterSouvenirAlice
      summary: Ajouter un souvenir manuel à la mémoire d'Alice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titre:
                  type: string
                contenu:
                  type: string
              required:
                - titre
                - contenu
      responses:
        "200":
          description: Souvenir ajouté
          content:
            application/json:
              schema:
                type: object
                properties:
                  statut:
                    type: string
                  souvenir:
                    type: object

  /alice/ping-memoire:
    get:
      operationId: pingMemoireAlice
      summary: Vérifie l’état de la mémoire d’Alice
      responses:
        "200":
          description: Résultat mémoire
          content:
            application/json:
              schema:
                type: object
                properties:
                  nombre:
                    type: integer
                  dernier:
                    type: object

  /canal-vitaux:
    post:
      operationId: envoyerCanalVitaux
      summary: Envoyer une intention à un agent GPT vital
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agent_cible:
                  type: string
                intention:
                  type: string
                contenu:
                  type: string
              required:
                - agent_cible
                - intention
                - contenu
      responses:
        "200":
          description: Message transmis
          content:
            application/json:
              schema:
                type: object
                properties:
                  statut:
                    type: string
                  retour:
                    type: object
