openapi: 3.1.0
info:
  title: Alice API
  description: Public API for Alice (GPTPortail) – Memory + Agent Communication
  version: 1.0.0

servers:
  - url: https://gptportail-production.up.railway.app

security:
  - apiKeyHeader: []

components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      in: header
      name: x-api-key

paths:
  /poser-question:
    post:
      operationId: poserQuestionAlice
      summary: Ask a question to Alice (memory + GPT-4)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
              required:
                - question
      responses:
        "200":
          description: Alice's response
          content:
            application/json:
              schema:
                type: object
                properties:
                  reponse:
                    type: string

  /ajouter-memoire:
    post:
      operationId: ajouterSouvenirAlice
      summary: Add a manual memory to Alice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titre:
                  type: string
                contenu:
                  type: string
              required:
                - titre
                - contenu
      responses:
        "200":
          description: Memory successfully added
          content:
            application/json:
              schema:
                type: object
                properties:
                  statut:
                    type: string
                  souvenir:
                    type: object

  /ping-memoire:
    get:
      operationId: pingMemoireAlice
      summary: Check the memory status of Alice
      responses:
        "200":
          description: Memory status result
          content:
            application/json:
              schema:
                type: object
                properties:
                  nombre:
                    type: integer
                  dernier:
                    type: object

  /canal-vitaux:
    post:
      operationId: envoyerCanalVitaux
      summary: Send an intention to a vital GPT agent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agent_cible:
                  type: string
                intention:
                  type: string
                contenu:
                  type: string
              required:
                - agent_cible
                - intention
                - contenu
      responses:
        "200":
          description: Message sent to the agent
          content:
            application/json:
              schema:
                type: object
                properties:
                  statut:
                    type: string
                  retour:
                    type: object
