openapi: 3.1.0
info:
  title: Prisma API
  version: 1.0.0
paths:
  /poser-question:
    post:
      summary: Poser une question à Prisma
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
              required:
                - question
      responses:
        '200':
          description: Réponse de Prisma
          content:
            application/json:
              schema:
                type: object
                properties:
                  réponse:
                    type: string
servers:
  - url: https://web-production-6594.up.railway.app
