openapi: 3.1.0
info:
  title: API PortailGPT Alice
  version: 1.0.0
  description: >
    API mémoire d'Alice – permet de poser une question, ajouter un souvenir,
    ou consulter l'état de la mémoire.

servers:
  - url: https://gptportail-production.up.railway.app

components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      in: header
      name: x-api-key
  schemas: {}  # Requis même vide pour GPT Builder

paths:
  /poser-question:
    post:
      operationId: poserQuestion
      summary: Poser une question à Alice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
              required:
                - question
      responses:
        '200':
          description: Réponse générée par Alice
          content:
            application/json:
              schema:
                type: object
                properties:
                  réponse:
                    type: string

  /ping-memoire:
    get:
      operationId: pingMemoire
      summary: Vérifie l’état de la mémoire
      responses:
        '200':
          description: Statut mémoire
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  total:
                    type: integer
                  uptime:
                    type: string

  /ajouter-memoire:
    post:
      operationId: ajouterMemoire
      summary: Ajouter un souvenir à la mémoire d’Alice
      security:
        - apiKeyHeader: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date-time
                titre:
                  type: string
                contenu:
                  type: string
              required:
                - date
                - titre
                - contenu
      responses:
        '200':
          description: Souvenir ajouté avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  statut:
                    type: string
