openapi: 3.1.0
info:
  title: API PortailGPT Alice
  version: 1.0.0
  description: >
    API mémoire d'Alice. Permet de poser une question,
    ajouter un souvenir ou consulter l’état de la mémoire.

servers:
  - url: https://gptportail-production.up.railway.app

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # ou 'API Key' selon préférence
  schemas: {}  # requis même vide par GPT Builder

paths:
  /poser-question:
    post:
      operationId: poserQuestion
      summary: Poser une question à Alice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
                  example: Quelle est la dernière connexion établie ?
      responses:
        '200':
          description: Réponse générée par Alice
          content:
            application/json:
              schema:
                type: object
                properties:
                  réponse:
                    type: string
        '400':
          description: Requête invalide
        '500':
          description: Erreur interne

  /ajouter-memoire:
    post:
      operationId: ajouterSouvenir
      summary: Ajouter un souvenir dans la mémoire d’Alice
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - date
                - titre
                - contenu
              properties:
                date:
                  type: string
                  format: date-time
                  example: 2025-04-30T10:00:00Z
                titre:
                  type: string
                  example: Connexion réussie avec BuilderGPT
                contenu:
                  type: string
                  example: Alice a confirmé l’établissement d’un lien stable avec BuilderGPT.
      responses:
        '200':
          description: Souvenir ajouté avec succès
        '403':
          description: Non autorisé
        '500':
          description: Erreur serveur

  /ping-memoire:
    get:
      operationId: pingMemoire
      summary: Vérifie l’état de la mémoire
      responses:
        '200':
          description: Statut mémoire
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  total:
                    type: integer
                  dernier_titre:
                    type: string
                  uptime:
                    type: string
                  version:
                    type: string
        '500':
          description: Erreur lecture mémoire
